### PR TITLE
FIX: Fix background

### PR DESCRIPTION
**Pull request by larsoner**
This sets the transparent bits to gray.

### CODE REVIEW

**Comment by larsoner** [comment]
The second commit fixes the PEP8 problems, if you've already fixed them (or want to do it yourself) feel free to just cherry-pick my first commit

**Comment by larsoner** [comment]
Latest commit makes it actually use the LUT of the cortex to choose the "under-colormap" color. It's probably not perfect but it should get us going for most use cases I think.

**Comment by larsoner** [comment]
(And I've modified the MEG example, which uses transparency, to show that it works.)

**Comment by sbitzer** [comment]
Cool stuff! I believe the code for the colorbar should move into the for-loop over surfaces, but apart from that it looks good. I will integrate your commits on Monday.

**Comment by larsoner** [comment]
Okay PR updated to have the commit that fixes background color for the vector example

**Comment by sbitzer** [comment]
I don't quite understand what was going wrong (some cortices don't have a lut associated with them?), but my test cases all came out nicely. :+1:

**Comment by larsoner** [comment]
Yes if there is no `curv` shown, it can just be a solid color instead of referencing the LUT at all (see the `_using_lut` usage and you'll see where)

**Pull request merged**
